# folder settings
source: .
destination: ./_site

# site settings
permalink: /:categories/:title
markdown: rdiscount

# site url
url: sparanoid.com

# force adding domain name site.url, used for CloudFront production only
# prod: true
prod: false

# used by images inserted in posts
file: http://rsrc.sparanoid.com

# used by specified background images
assets-cdn: http://a2.sparanoid.com

# used by css url in default.html and index.xml
css-path: css

# custom vars, most of them are used by index.xml
name: Sparanoid
full-name: Tunghiao Liu
email: info@sparanoid.com
slogan: I make things that don't suck.
twitter: sparanoid

# fire up a localhost and auto generate when files change
auto: true
server: ture
server_port: 4321

# exclude files for generated site
exclude: 
- README.md
- LICENSE
- Rakefile